services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    env_file:
      - /seletivo/seletivo.env
    ports:
      - "9932:5432"
    volumes:
      - postgres_vol:/var/lib/postgresql/18/docker
    networks:
      - seletivo_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_vol:

networks:
  seletivo_net:
    driver: bridge
