services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    env_file:
      - seletivo.env
    ports:
      - "9932:5432"
    volumes:
      - postgres_vol:/var/lib/postgresql/18/docker
    networks:
      - seletivo_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_vol:/data
    command: server /data --console-address ":9001"
    networks:
      - seletivo_net

volumes:
  postgres_vol:
  minio_vol:

networks:
  seletivo_net:
    driver: bridge
